#!/bin/sh

set -e

echo "Creating new buildpack version"
pack buildpack package wwwhisper/wwwhisper-cnb --path buildpack # --config  ./package.toml

echo "Pushing the new version to docker"
docker push wwwhisper/wwwhisper-cnb

echo "Putting the new version in the CNB registry"
pack buildpack register wwwhisper/wwwhisper-cnb -v
