#!/bin/sh

set -e

echo "Packaging a buildpack into Docker image"
pack buildpack package wwwhisper/wwwhisper-cnb --path buildpack # --config  ./package.toml

echo "Pushing the new version to docker"
docker push wwwhisper/wwwhisper-cnb

echo "Publishing buildpack to CNB registry"
pack buildpack register wwwhisper/wwwhisper-cnb -v
